services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aus-job-board-frontend:latest
    # environment:
    #   - REACT_APP_API_URL=http://54.79.190.69/api

  nginx:
    ports:
      - "80:80"  # For HTTP
      - "443:443" # for HTTPS
    volumes:
      - ./nginx/job-board.conf:/etc/nginx/conf.d/default.conf  # Mount the Nginx configuration file
      - ./backend/uploads:/app/uploads  # Mount the uploads directory
      - nginx_cache:/var/cache/nginx  # Mount the Nginx cache directory
    # We don't need to mount ./frontend/build:/app/frontend/build anymore because 
    # the static files are copied into the Nginx image during the build process
    depends_on:
      - frontend

volumes:
  nginx_cache:  # Define the nginx_cache volume