version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - FLASK_ENV=staging
      - DB_HOST=${STAGING_DB_HOST}
      - DB_PORT=${STAGING_DB_PORT}
      - DB_NAME=${STAGING_DB_NAME}
      - DB_USER=${STAGING_DB_USER}
      - DB_PASSWORD=${STAGING_DB_PASSWORD}
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: aus-job-board-frontend:staging

  postgres:
    profiles: ["do-not-run-in-staging"]
    image: postgres:15
    command: ["echo", "Postgres is disabled in staging"]