
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    command: npm start
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - ./nginx/job-board.dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"