services:
  frontend:
    build: ./frontend # Build the frontend service from the Dockerfile in the ./frontend directory
    volumes:
      - ./frontend:/app # mounting the local frontend directory to /app in the container for live updates
      - /app/node_modules # added volume for /app/node_modules to prevent overwriting the installed packages
    environment:
      # - REACT_APP_API_URL=http://localhost/api
      REACT_APP_API_URL=http://54.79.190.69
    command: npm start # command to run the development server
    depends_on:
      - backend # Ensure backend is started before frontend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DB_HOST=postgres
      - DB_NAME=job_board
      - DB_USER=jai
      - DB_PASSWORD=techboard
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY:-1234567890}
    ports:
      - "4040:4040"
    depends_on:
      - postgres
      - redis

  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: job_board
      POSTGRES_USER: jai
      POSTGRES_PASSWORD: techboard
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  nginx:
    build: ./nginx # Build the nginx service using the Dockerfile in ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/job-board.conf:/etc/nginx/conf.d/default.conf # Mount Nginx configuration
    depends_on:
      - frontend # Ensure frontend is started before nginx
      - backend # Ensure backend is started before nginx

volumes:
  postgres_data: # Define a named volume for PostgreSQL data persistence
