services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app # Dev mounts the local directory for live reloading, which isn't needed in production
      - /app/node_modules 
    command: npm start
    depends_on:
      - backend

  nginx:
    volumes:
      - ./nginx/job-board.dev.conf:/etc/nginx/conf.d/default.conf # Mount the Nginx DEV configuration file
    ports:
      - "80:80"