
FROM nginx:alpine

RUN mkdir -p /var/cache/nginx

COPY job-board.conf /etc/nginx/conf.d/default.conf

COPY --from=aus-job-board-frontend:latest /usr/share/nginx/html /usr/share/nginx/html

EXPOSE 80 

CMD ["nginx", "-g", "daemon off;"]