"""initial migration

Revision ID: 217ea4cfd126
Revises: b78cc3f22723
Create Date: 2024-09-15 11:04:33.816648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217ea4cfd126'
down_revision = 'b78cc3f22723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_technologies', schema=None) as batch_op:
        batch_op.drop_index('job_technologies_job_id_idx')
        batch_op.drop_index('job_technologies_technology_id_idx')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('jobs_city_idx')
        batch_op.drop_index('jobs_experience_level_idx')
        batch_op.drop_index('jobs_search_vector_idx', postgresql_using='gin')
        batch_op.drop_index('jobs_specialization_idx')
        batch_op.drop_index('jobs_work_location_idx')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('jobs_work_location_idx', ['work_location'], unique=False)
        batch_op.create_index('jobs_specialization_idx', ['specialization'], unique=False)
        batch_op.create_index('jobs_search_vector_idx', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index('jobs_experience_level_idx', ['experience_level'], unique=False)
        batch_op.create_index('jobs_city_idx', ['city'], unique=False)

    with op.batch_alter_table('job_technologies', schema=None) as batch_op:
        batch_op.create_index('job_technologies_technology_id_idx', ['technology_id'], unique=False)
        batch_op.create_index('job_technologies_job_id_idx', ['job_id'], unique=False)

    # ### end Alembic commands ###
