"""Initial migration after reset

Revision ID: 4c6ee2cd04e9
Revises: 
Create Date: 2024-09-24 11:29:17.939255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6ee2cd04e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
