"""Update Recruiter Model to add 'position' as a field

Revision ID: 6f89c69db19e
Revises: 93158df597ad
Create Date: 2024-06-22 22:44:48.598974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f89c69db19e'
down_revision = '93158df597ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
