"""Add embedding column to jobs and candidates tables

Revision ID: 93158df597ad
Revises: 9ec1dfbb5e37
Create Date: 2024-06-21 17:12:21.959795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93158df597ad'
down_revision = '9ec1dfbb5e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('work_experience',
               existing_type=sa.TEXT(),
               type_=sa.String(length=800),
               existing_nullable=True)

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('jobs_search_idx', postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('jobs_search_idx', ['search_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.alter_column('work_experience',
               existing_type=sa.String(length=800),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
