"""empty message

Revision ID: c3b518f5b4ef
Revises: f90cb0a4ce93
Create Date: 2024-04-28 20:49:34.794008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3b518f5b4ef'
down_revision = 'f90cb0a4ce93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Enum('VIC', 'NSW', 'ACT', 'WA', 'QLD', 'NT', 'TAS', 'SA', name='state_enum'), nullable=False))
        batch_op.add_column(sa.Column('country', sa.Enum('Australia', 'New Zealand', name='country_enum'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seekers', schema=None) as batch_op:
        batch_op.drop_column('country')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
