"""added verification_code and verification_code_expiry to Company

Revision ID: cada8eec1ad4
Revises: 4c6ee2cd04e9
Create Date: 2024-09-25 05:39:40.649723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cada8eec1ad4'
down_revision = '4c6ee2cd04e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('verification_code_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_column('verification_code_expiry')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
