"""Remove city, state, country and add website_url

Revision ID: dc5bcd043dd3
Revises: c69336f7be7a
Create Date: 2024-05-26 17:47:45.046992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc5bcd043dd3'
down_revision = 'c69336f7be7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('companies', sa.Column('website_url', sa.String(length=255), nullable=True))
    op.create_check_constraint('ck_companies_website_url', 'companies', "website_url ~ '^(https?://)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([/\\w\\.-]*)*/?$'")
    op.drop_column('companies', 'city')
    op.drop_column('companies', 'state')
    op.drop_column('companies', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('companies', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('companies', sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('ck_companies_website_url', 'companies', type_='check')
    op.drop_column('companies', 'website_url')
    # ### end Alembic commands ###
