"""Consolidate schema changes for Seeker model

Revision ID: ee4ecef0f197
Revises: 2c0b175bfc39
Create Date: 2024-07-03 15:15:44.221235

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = 'ee4ecef0f197'
down_revision = '2c0b175bfc39'
branch_labels = None
depends_on = None


def upgrade():
    # Create the vector extension if it doesn't exist
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', Vector(1536), nullable=True))

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('size', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', Vector(1536), nullable=True))

    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recruiters', schema=None) as batch_op:
        batch_op.drop_column('position')

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('description')
        batch_op.drop_column('address')
        batch_op.drop_column('size')
        batch_op.drop_column('country')

    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # Drop the vector extension
    op.execute('DROP EXTENSION IF EXISTS vector')

    # ### end Alembic commands ###