"""Add new fields - overview, responsibilities, requirements, hourly_range, daily_range, job_arrangement, contract_duration to Jobs model

Revision ID: f89aee93fed6
Revises: dfc5d09b6430
Create Date: 2024-08-06 08:44:11.751310

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f89aee93fed6'
down_revision = 'dfc5d09b6430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_backup')
    op.drop_table('jobs_backup1')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('responsibilities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('job_arrangement', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('contract_duration', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('hourly_range', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('daily_range', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('daily_range')
        batch_op.drop_column('hourly_range')
        batch_op.drop_column('contract_duration')
        batch_op.drop_column('job_arrangement')
        batch_op.drop_column('requirements')
        batch_op.drop_column('responsibilities')
        batch_op.drop_column('overview')

    op.create_table('jobs_backup1',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recruiter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_type', postgresql.ENUM('premium', 'normal', name='job_type'), autoincrement=False, nullable=True),
    sa.Column('industry', postgresql.ENUM('Government', 'Banking & Financial Services', 'Fashion', 'Mining', 'Healthcare', 'IT - Software Development', 'IT - Data Analytics', 'IT - Cybersecurity', 'IT - Cloud Computing', 'IT - Artificial Intelligence', 'Agriculture', 'Automotive', 'Construction', 'Education', 'Energy & Utilities', 'Entertainment', 'Hospitality & Tourism', 'Legal', 'Manufacturing', 'Marketing & Advertising', 'Media & Communications', 'Non-Profit & NGO', 'Pharmaceuticals', 'Real Estate', 'Retail & Consumer Goods', 'Telecommunications', 'Transportation & Logistics', name='industry_type'), autoincrement=False, nullable=True),
    sa.Column('salary_range', postgresql.ENUM('20000 - 40000', '40000 - 60000', '60000 - 80000', '80000 - 100000', '100000 - 120000', '120000 - 140000', '140000 - 160000', '160000 - 180000', '180000 - 200000', '200000 - 220000', '220000 - 240000', '240000 - 260000', '260000+', name='salary_range_type'), autoincrement=False, nullable=True),
    sa.Column('salary_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('work_location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('min_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('jobpost_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('work_rights', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('embedding', matching.custom_types.Vector(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_arrangement', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contract_duration', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hourly_range', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_range', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    op.create_table('jobs_backup',
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recruiter_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('specialization', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('job_type', postgresql.ENUM('premium', 'normal', name='job_type'), autoincrement=False, nullable=True),
    sa.Column('industry', postgresql.ENUM('Government', 'Banking & Financial Services', 'Fashion', 'Mining', 'Healthcare', 'IT - Software Development', 'IT - Data Analytics', 'IT - Cybersecurity', 'IT - Cloud Computing', 'IT - Artificial Intelligence', 'Agriculture', 'Automotive', 'Construction', 'Education', 'Energy & Utilities', 'Entertainment', 'Hospitality & Tourism', 'Legal', 'Manufacturing', 'Marketing & Advertising', 'Media & Communications', 'Non-Profit & NGO', 'Pharmaceuticals', 'Real Estate', 'Retail & Consumer Goods', 'Telecommunications', 'Transportation & Logistics', name='industry_type'), autoincrement=False, nullable=True),
    sa.Column('salary_range', postgresql.ENUM('20000 - 40000', '40000 - 60000', '60000 - 80000', '80000 - 100000', '100000 - 120000', '120000 - 140000', '140000 - 160000', '160000 - 180000', '180000 - 200000', '200000 - 220000', '220000 - 240000', '240000 - 260000', '260000+', name='salary_range_type'), autoincrement=False, nullable=True),
    sa.Column('salary_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('work_location', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('min_experience_years', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('tech_stack', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('expiry_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('jobpost_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('work_rights', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('embedding', matching.custom_types.Vector(), autoincrement=False, nullable=True),
    sa.Column('overview', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('responsibilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_arrangement', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('contract_duration', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('hourly_range', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('daily_range', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
