name: CI/CD Pipeline

on:
  push:
    branches:
      - llama-integration

jobs:
  build:
    # ... (keep the build job as is)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./frontend/build

      - name: Debug - Print SSH Key
        run: |
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" | sed 's/./*/g'
          echo "First line of SSH key:"
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" | head -n 1

      - name: Save private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LIGHTSAIL_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub

      - name: Debug - List SSH files
        run: ls -la ~/.ssh

      - name: Debug - Test SSH connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "echo Debug SSH connection test"
        continue-on-error: true

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Debug - Test SSH after key installation
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "echo Debug SSH connection test after key installation"
        continue-on-error: true

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "./frontend/build"
          target: "./OceaniaDevs/frontend/build"
          debug: true

      # ... (keep the rest of the workflow as is)

      # Uncomment the following step when SSH connection is successful
      # - name: SSH and restart Docker containers
      #   if: steps.ssh_key_path.outcome == 'success' || steps.ssh_key.outcome == 'success' || steps.ssh_insecure.outcome == 'success' || steps.ssh_alternative.outcome == 'success'
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.LIGHTSAIL_HOST }}
      #     username: ${{ secrets.LIGHTSAIL_USER }}
      #     key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
      #     script: |
      #       cd ~/OceaniaDevs
      #       docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
      #       docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build