name: CI/CD Pipeline

on:
  push:
    branches:
      - llama-integration

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          cd frontend
          npm install

      - name: Build the React app
        env:
          CI: false
        run: |
          cd frontend
          npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./frontend/build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: ./frontend/build

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: replace

      - name: Debug - Check SSH key
        run: ssh-keygen -l -f ~/.ssh/id_rsa

      - name: Debug - Check known_hosts
        run: cat ~/.ssh/known_hosts

      - name: Debug SSH connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ${{ secrets.LIGHTSAIL_USER }}@${{ secrets.LIGHTSAIL_HOST }} "echo SSH connection successful"
        continue-on-error: true

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          source: "./frontend/build"
          target: "./OceaniaDevs/frontend/build"
          debug: true

      # Uncomment the following step when SSH connection is successful
      # - name: SSH and restart Docker containers
      #   if: steps.ssh_key_path.outcome == 'success' || steps.ssh_key.outcome == 'success' || steps.ssh_insecure.outcome == 'success' || steps.ssh_alternative.outcome == 'success'
      #   uses: appleboy/ssh-action@v0.1.4
      #   with:
      #     host: ${{ secrets.LIGHTSAIL_HOST }}
      #     username: ${{ secrets.LIGHTSAIL_USER }}
      #     key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
      #     script: |
      #       cd ~/OceaniaDevs
      #       docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
      #       docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build